import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Income and Expense Calculator',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
          <link rel="icon" type="image/svg+xml" href="/icon.svg" />
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
